[package]
name = "hwc"
version = "0.1.0"
edition = "2021"

[features]
console = []

[dependencies]
wallpaper = "3.2.0"
device_query = "2.1.0"
toml = "0.8.19"
serde = { version = "1.0.210", features = ["derive"] }
log = "0.4.22"
env_logger = "0.11.5"
log-panics = "2.1.0"
imghdr = "0.7.0"